# Generated by Django 4.0.2 on 2022-02-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='key',
            field=models.CharField(default='', max_length=200),
        ),
    ]
