# Generated by Django 4.0.2 on 2022-02-14 21:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0002_image_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='key',
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
